vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set clipboard=unnamedplus")
vim.cmd("set relativenumber")
vim.cmd("set number")
vim.g.mapleader = " "
vim.keymap.set({'n','v'}, "<C-y>", '"+y')
vim.keymap.set({'n','v'}, "<C-p>", '"+p')
vim.keymap.set({'n','v'}, "<leader>v", ':vnew<CR>')
vim.keymap.set({'n','v'}, "<leader>h", ':new<CR>')
vim.diagnostic.config({virtual_text = true})
